name: Deploy Discos App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push MySQL image
        uses: docker/build-push-action@v5
        with:
          context: ./mysql
          file: ./mysql/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sqldiscos:v1

      - name: Build and push PHP image
        uses: docker/build-push-action@v5
        with:
          context: ./php
          file: ./php/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/phpdiscos:v1

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            cd /var/www/html/ExamenDespliegueEj2
            docker-compose pull
            docker-compose up -d --remove-orphans